DataConverter/ConvertData/urls.py
from django.urls import path
from . import views

app_name = "QuickConvert"
urlpatterns = [
    path('convert/', views.convert, name="convert"),
    path('data-form/', views.data_form, name="data_form")
]

DataConverter/DataConverter/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("QuickConvert/", include("ConvertData.urls")),
    path('admin/', admin.site.urls),
]

DataConverter/ConvertData/models/data.py
from django.db import models

class DataSource(models.Model):
  soure_id= models.AutoField(primary_key=True, blank=False)
  description = models.TextField(blank=False) 
  source_type = models.CharField(max_length=50,blank=False)

class DataEntry(models.Model):
  class Status(models.TextChoices):
    PENDING = 'PD', 'Pending'
    FINISHED = 'FN', 'Finished'
    ERROR = 'ER', 'ERROR'
  entry_id = models.AutoField(primary_key=True,blank=False)
  source_id = models.ForeignKey(DataSource, on_delete=models.CASCADE)
  received_at = models.DateTimeField(auto_now=True,blank=False)
  status = models.CharField(max_length=2, choices=Status.choices, default= Status.PENDING)
  updated_at = models.DateTimeField(auto_now=True)


class NormalizeData(models.Model):
  data_id = models.AutoField(primary_key=True, blank=False)
  entry_id = models.ForeignKey(DataEntry, on_delete=models.CASCADE)
  company_name = models.CharField(max_length=200, blank=False)
  location = models.CharField(blank=False, max_length=300)
  product = models.CharField(blank=False, max_length=200)
  quantity = models.IntegerField(blank=None)
  price = models.IntegerField(blank=None)

DataConverter/ConvertData/views.py
from django import forms
from django.urls import reverse
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_protect
import pandas as pd
import json
from io import StringIO
import csv


def data_form(request):
  return render(request, "Data.html")

@csrf_protect 
def convert(request):
  if request.method == "POST":
    raw_data = request.POST.get("data", " ")
    try:
      csv_file = StringIO(raw_data)  
      reader = csv.DictReader(csv_file)
      json_data = list(reader)
      return render(request, "Data.html", {"json_data":json_data})
    except(ValueError):
      print("Data was not submitted")
  return render(request, "Data.html")
  

DataConverter/ConvertData/templates/Data.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body>
    <div id="form-main">
      <div id="form-div">
        <form
          class="form"
          id="form1"
          action="{% url 'QuickConvert:convert'%}"
          method="post"
        >
          {% csrf_token %}
          <p class="text">
            <textarea
              name="data"
              class="validate[required,length[6,300]] feedback-input"
              id="data"
              placeholder="Enter Data"
            ></textarea>
          </p>
          <div class="submit">
            <input type="submit" id="button-blue" />
            <div class="ease"></div>
          </div>
        </form>
      </div>
    </div>
    <div class="window">
      {% if json_data %}
      <p>{{json_data}}</p>
      {% endif %}
    </div>
  </body>
</html>